<?php

include_once('background_workflow.features.inc');


function background_workflow_init() {
  if(arg(0) == 'node' && is_numeric(arg(1))) {
    $node = node_load(arg(1));
    if($node->type == "background") {
      background_workflow_apply($node);
    }
    
  }
  elseif(arg(0) != 'admin') {
    background_workflow_apply();
  }
}

function background_workflow_apply($node = NULL) {
  if(!$node) {
    $node = background_workflow_random();
  }
  if($node) {
  dynamic_backgrounds_apply('/' . $node->field_background_image[0]['filepath'], $node->field_background_color[0]['value'],
    $node->field_background_position[0]['value'], $node->field_background_repeat[0]['value'], 
    $node->field_background_attachment[0]['value']);
  }
}

function background_workflow_random() {

  $sql = "SELECT node.nid AS nid,
    RAND() AS _random
    FROM node node 
    LEFT JOIN workflow_node workflow_node ON node.nid = workflow_node.nid
    WHERE workflow_node.state_name = 'background_approvals_approved' 
    ORDER BY _random ASC 
    LIMIT 1";
  return node_load(db_result(db_query($sql)));
  
}

function background_workflow_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == "background_node_form") {
  //kpr($form);
  unset($form['buttons']);
  }
}

function background_workflow_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($node->type == "background" && $op == "insert") {
    drupal_set_message("Does your background look like awesome sauce?  Click the Move to \"Review for Approval\" button.", "error");       
  }
}
